---@module "overseer"
---@module "dap"

---@class OverseerOptions: overseer.TaskDefinition
---@field cwd? string Working directory to run in
---@field env? table<string, string> Additional environment variables
---@field strategy? overseer.Serialized Definition for a run Strategy
---@field metadata? table Arbitrary metadata for your own use
---@field default_component_params? table<string, any> Default values for component params
---@field components? overseer.Serialized[] List of components to attach. Defaults to `{"default"}`
---@field ephemeral? boolean Indicates that this task was generated by another task (e.g. with run_after)

--- See available gdb options at: https://sourceware.org/gdb/current/onlinedocs/gdb.html/Debugger-Adapter-Protocol.html
---@class DapOptions: dap.Configuration
---@field type string
---@field request? "launch"|"attach"
---@field name? string Can be used to overwrite the name set in Task
---@field [string] any

---@class TaskContext
---@field is_overseer_task? true
---@field is_dap_task? true
---@field [string] any

---@class Task
---@field name string Name of the task. Defaults to the cmd output
---@field enabled? boolean
---@field resolve_context? fun(): TaskContext|nil The phase when the user is asked for input. Returns context for the cmds to use or nil if failed or cancelled
---@field pre_run_cmd? fun(context: table): string[] Returns a list of a cmd and args to run before the main cmd
---@field cmd fun(context: table): string[] Returns a list of a cmd and args
---@field post_run_cmd? fun(context: table, status?: string): string[] Returns a list of a cmd and args to run after the main cmd
---@field overseer? { enabled: boolean, options?: OverseerOptions } 'options' is used by all cmds
---@field dap? { enabled: true, options: DapOptions } | { enabled: false, options?: DapOptions }

local M = {
	enabled = true,
	overseer = {
		enabled = true,
		options = {
			ephemeral = true,
			components = {
				{ "on_exit_set_status", "default" },
			},
		},
	},
	dap = {
		options = {
			request = "launch",
			cwd = "${workspaceFolder}",
		},
	},
}

return M
